export const SELECT_POKEMON = "SELECT_POKEMON";
export const SELECT_SAVED_POKEMON = "SELECT_SAVED_POKEMON";
export const UNSELECT_POKEMONS = "UNSELECT_POKEMONS";
export const COMPARE_POKEMON =  "COMPARE_POKEMON";
export const SAVE_POKEMON = "SAVE_POKEMON";